-- MySQL Script generated by MySQL Workbench
-- Tue May  3 13:12:43 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema gasp
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gasp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gasp` DEFAULT CHARACTER SET utf8 ;
USE `gasp` ;

-- -----------------------------------------------------
-- Table `gasp`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gasp`.`users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(256) NOT NULL,
  `creation_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gasp`.`statuses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gasp`.`statuses` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gasp`.`jobs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gasp`.`jobs` (
  `id` BINARY(16) NOT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  `name` VARCHAR(128) NOT NULL,
  `error_message` VARCHAR(512) NULL,
  `status_id` INT UNSIGNED NOT NULL,
  `creation_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_jobs_users_idx` (`user_id` ASC),
  INDEX `fk_jobs_statuses1_idx` (`status_id` ASC),
  CONSTRAINT `fk_jobs_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `gasp`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_jobs_statuses1`
    FOREIGN KEY (`status_id`)
    REFERENCES `gasp`.`statuses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `gasp` ;

-- -----------------------------------------------------
-- function uuid_to_bin
-- -----------------------------------------------------

DELIMITER $$
USE `gasp`$$
CREATE DEFINER=`root`@`localhost` FUNCTION `uuid_to_bin`(s CHAR(36)) RETURNS binary(16)
    DETERMINISTIC
BEGIN
RETURN UNHEX(REPLACE(s,'-',''));
END$$

DELIMITER ;

-- -----------------------------------------------------
-- function bin_to_uuid
-- -----------------------------------------------------

DELIMITER $$
USE `gasp`$$
CREATE DEFINER=`root`@`localhost` FUNCTION `bin_to_uuid`(b BINARY(16)) RETURNS char(36) CHARSET utf8
    DETERMINISTIC
BEGIN
  DECLARE hex CHAR(32);
  SET hex = HEX(b);
  RETURN LOWER(CONCAT(LEFT(hex, 8), '-', MID(hex, 9,4), '-', MID(hex, 13,4), '-', MID(hex, 17,4), '-', RIGHT(hex, 12)));
END$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `gasp`.`statuses`
-- -----------------------------------------------------
START TRANSACTION;
USE `gasp`;
INSERT INTO `gasp`.`statuses` (`id`, `name`) VALUES (DEFAULT, 'created');
INSERT INTO `gasp`.`statuses` (`id`, `name`) VALUES (DEFAULT, 'queued');
INSERT INTO `gasp`.`statuses` (`id`, `name`) VALUES (DEFAULT, 'started');
INSERT INTO `gasp`.`statuses` (`id`, `name`) VALUES (DEFAULT, 'cancel_requested');
INSERT INTO `gasp`.`statuses` (`id`, `name`) VALUES (DEFAULT, 'cancelled');
INSERT INTO `gasp`.`statuses` (`id`, `name`) VALUES (DEFAULT, 'failed');
INSERT INTO `gasp`.`statuses` (`id`, `name`) VALUES (DEFAULT, 'succeeded');
INSERT INTO `gasp`.`statuses` (`id`, `name`) VALUES (DEFAULT, 'quarantined');

COMMIT;

